[scene]: the_real_world_bedroom
[role]: LuoYue
[item]: none
[dialog]: 這是什麼破結局啊！寫的也太爛了吧！我可憐的小祁祁啊TAT
[choice]: none
[scene]: the_real_world_bedroom
[role]: Aside
[item]: none
[dialog]: 寧靜的夜晚，H市的一間小套房突然傳來女孩的怒吼。躺在床上的洛玥越想越憋屈，突然想幹些什麼事。
[choice]: 1,first_first
[scene]: the_real_world_bedroom
[role]: Aside 
[item]: smartphone
[dialog]: 猛地起身拿起方才扔在一旁的手機，劈裡啪啦的在評論區留言。
[choice]: none
[scene]: the_real_world_bedroom
[role]: LuoYue(smartphone)
[item]: smartphone
[dialog]: 小祁祁小時候被拋棄已經夠可憐了，好不容易靠自己努力創立了自己的商業帝國，誰還會稀罕墨家啊，就為了那有跟沒有一樣的親情還黑化成反派(☉д⊙)作者大大你寫的也太不合理了ヽ(`Д´)ﾉ
[choice]: none
[scene]: the_real_world_bedroom
[role]: Aside
[item]: none
[dialog]: 發洩完的洛玥長舒出一口濁氣，但心裡還是悶悶的，哪哪都不得勁，為了緩解情緒，她決定去泡個澡轉換一下心情。
[choice]: 1,first_second
[scene]: the_real_world_bathroom
[role]:  Aside
[item]: none
[dialog]: 嘩～洛玥泡在水裡，腦子裡還是沒忍住想著小說裡的情節。前些日子公司事情多到令人頭疼，這幾日好不容易忙完的洛玥總算能放個長假休息，正巧她在網上刷到一本名叫《墨韻南歌》的小說，劇情完全擊中她的喜好，於是她直接熬了兩個通宵看完了這部小說。結局是好的，但萬萬沒想到她最喜歡的角色下場這麼慘！就在洛玥越想越生氣時，手機屏幕突然傳來訊息聲。一條陌生訊息映入眼簾。
[choice]: none
[scene]: the_real_world_bathroom
[role]: smatphone_message
[item]: smartphone
[dialog]: 親，收到你的反饋啦！是否願意幫助反派改變命運呢？
[choice]: 2,first_third
[[first_third.yes]]
[scene]: the_real_world_bathroom
[role]:  Aside
[item]: smartphone
[dialog]: 看著手機裡的訊息洛玥覺得莫名其妙，正打算不理會這則訊息，卻沒來由的頭暈，一沒留神就點下了屏幕中的【是】，下一秒洛玥人就昏迷過去了，閉上眼的最後一秒，洛玥只有一個念頭。
[choice]: none
[scene]: the_real_world_bathroom
[role]:  LuoYue(think)
[item]: none
[dialog]: 太生氣到忘記泡澡不能泡太久了…
[choice]: none
[scene]: the_real_world_bathroom
[role]:  Aside
[item]: none
[dialog]: 因為暈過去了，洛玥並沒有注意到手機又來了一條訊息…
[choice]: none
[scene]: the_real_world_bathroom
[role]:  smatphone_message
[item]: smartphone
[dialog]: 好的，親。正在傳送中呦～祝您任務順利！
[choice]: none
[[first_third.no]]
[scene]: the_real_world_bathroom
[role]:  Aside
[item]: smartphone
[dialog]: 看著手機裡的訊息洛玥覺得莫名其妙，打算不理會這則訊息。
[choice]: none
[scene]: the_real_world_bathroom
[role]:  LuoYue
[item]: none
[dialog]: 什麼啊，現在真的什麼詐騙手法都有耶…
[choice]: none
[scene]: the_real_world_bathroom
[role]:  Aside
[item]: smartphone
[dialog]: 邊想著洛玥邊順手點了【否】。尋思著泡澡時間也差不多了，便起身洗漱上床睡覺補眠去了。
[choice]: none
[scene]: end
[dialog]: 洛玥未穿越，小說世界未有任何變化 <--結局1 End.-->
[scene]: hospital
[role]:  Aside
[item]: none
[dialog]: 洛玥一醒來發現自己在一個陌生的環境，看著白花花的牆她意識到自己似乎是在醫院。
[choice]: none
[scene]: hospital
[role]:  LinZhou
[item]: none
[dialog]: 你總算是醒來了！
[choice]: none
[scene]: hospital
[role]:  Aside
[item]: none
[dialog]: 一道聲音把洛玥嚇了一跳，她這才發現她的床邊有兩個男人，說話的是站著的那個，此時他急急忙忙的出去喊醫生來給她檢查。洛玥還沒來得及開口，她腦子裡就響起一道聲音。
[choice]: none
[scene]: hospital
[role]:  System
[item]: none
[dialog]: 歡迎宿主來到小說副本世界！妳的任務是拯救反派言煜祁，阻止他黑化，改變他死亡的命運！
[choice]: none
[scene]: hospital
[role]: Aside 
[item]: none
[dialog]: 畢竟也是網路小說資深讀者，洛玥很快就反應過來發生什麼事了。
[choice]: none
[scene]: hospital
[role]:  LuoYue(think)
[item]: none
[dialog]: 你是…系統嗎？我怎麼會進來？我可以直接回去嗎？完成任務對我有什麼好處？
[choice]: none
[scene]: hospital
[role]:  System
[item]: none
[dialog]: 沒錯喔主人，我是妳親愛的系統～但非必要我是不會出現噠！至於妳為什麼會進來…自然是因為妳同意了我們的任務呀～完成任務可以就有機會許願，任何願望都能替妳實現喔～至於現在就回到現實世界嘛…這是不行的喔，一旦進入副本世界就視同任務開始，只有成功或者失敗才能決定宿主的去留喔！
[choice]: none
[scene]: hospital
[role]:  LuoYue(think)
[item]: none
[dialog]: …行吧，那我該怎麼拯救言煜祁？你應該有資訊提供給我吧？比如我這身體的身家背景？
[choice]: none
[scene]: hospital
[role]:  System
[item]: none
[dialog]: 怎麼拯救反派這個要靠主人妳自己摸索喔，我只負責提供一些必須知道的資訊。不過因為主人妳是新手，而且本遊戲副本都是身穿，所以給妳的新手禮包就是可以自己設定自己的身分，包含身世學歷等等都可以自己設定喔！
[choice]: none
[scene]: hospital
[role]:  Aside
[item]: none
[dialog]: 本來洛玥對於自己有這樣的機遇還覺得挺興奮，沒想到自己的這個系統這麼廢，不禁一陣無語，隨即開啟設定給自己新身分。其實洛玥在聽到要拯救反派時就已經在構思該如何尋個方法接近言煜祁了，思來想去還是到他身邊當秘書或許是最好的方法。在原世界時，洛玥雖然是孤兒，但也是靠著自己的努力成功上到世界最頂級M大，所以洛玥想著憑藉自己的原學歷去入職言煜祁的公司應該綽綽有餘，於是對於自己的身家背景她很直接的照著自己的原狀況填寫。等到她處理完後，方才去找醫生的那個男人正好帶著醫生回來了。醫生給洛玥檢查確認沒問題就走了，這時洛玥才得空觀察身邊的兩個男人。
[choice]: none
[scene]: hospital
[role]:  LinZhou
[item]: none
[dialog]: 洛小姐，好險您只是低血糖，沒事就好。
[choice]: none
[scene]: hospital
[role]:  Aside
[item]: none
[dialog]: 說話的是方才找醫生的那個男人。
[choice]: none
[scene]: hospital
[role]:  LuoYue
[item]: none
[dialog]: 謝謝你們，請問你們是…？
[choice]: none
[scene]: hospital
[role]:  LinZhou
[item]: none
[dialog]: 我叫林舟，這是言氏集團的總裁言煜祁。今天您就是昏倒在總裁的車子旁邊才被我們發現的。
[choice]: none
[scene]: hospital
[role]:  Aside
[item]: none
[dialog]: 洛玥聽到這名字不禁有點驚訝。
[choice]: none
[scene]: hospital
[role]:  LuoYue(think)
[item]: none
[dialog]: 得來全不費工夫？這麼容易就遇到目標任務嗎？
[choice]: none
[scene]: hospital
[role]:  Aside
[item]: none
[dialog]: 她打量著坐在椅子上西裝筆挺的男人，男人五官精緻，劍眉星目，眉如墨染，眸如星辰，整個人散發出一種英俊而神秘的氣質。他的眉毛濃密如劍，眉形鋒利，增添了幾分英氣；他的眼睛明亮有神，宛如夜空中的星辰，透露出深邃的神采。整體形象給人一種既俊秀又充滿力量的感覺，顯得獨特而富有魅力。或許是感受到她的視線，原本低著頭在看手機訊息的言煜祁抬起頭來看向她，洛玥看到趕緊收回目光。
[choice]: 2,second_first
[[second_first.find_job]]
[scene]: hospital
[role]:  LuoYue
[item]: none
[dialog]: 我…我最近剛回國，忙著找工作，沒怎麼吃飯，所以就…
[choice]: none
[scene]: hospital
[role]:  Aside
[item]: resume
[dialog]: 言煜祁聞言，拿起放在旁邊，不知道何時出現的簡歷看了看。這一幕看的洛玥一愣。
[choice]: none
[scene]: hospital
[role]:  LuoYue(think)
[item]: none
[dialog]: 系統，那個簡歷是你弄出來的嗎？
[choice]: none
[scene]: hospital
[role]:  System
[item]: none
[dialog]: 是的喔主人，因為妳設定是剛回國在找工作的海歸，所以有安排好簡歷在你身邊喔！
[choice]: none
[scene]: hospital
[role]:  Aside
[item]: none
[dialog]: 這時言煜祁將簡歷遞給一旁的林舟。
[choice]: none
[scene]: hospital
[role]:  YanYuQi
[item]: none
[dialog]: 你是M大管理學院畢業的？
[choice]: none
[scene]: hospital
[role]:  LuoYue
[item]: none
[dialog]: …是
[choice]: none
[scene]: hospital
[role]:  YanYuQi
[item]: none
[dialog]: 我缺個秘書，有興趣嗎？
[choice]: 2,second_first_first
[[second_first_first.yes]]
[scene]: hospital
[role]:  Aside
[item]: none
[dialog]: 洛玥驚到眼睛睜大，沒想到自己心裡所預期的計畫，甚至都還沒開始實施，就已經完成第一步了。
[choice]: none
[scene]: hospital
[role]:  LuoYue(think)
[item]: none
[dialog]: 統子統子，你不會給我開了什麼金手指吧？
[choice]: none
[scene]: hospital
[role]:  System
[item]: none
[dialog]: 沒有喔主人，新手禮包除了可以讓妳自己設定自身消息外，並沒有其他功能了喔！
[choice]: none
[scene]: hospital
[role]:  Aside
[item]: none
[dialog]: 洛玥忍不住在心裡放了白眼，也是沒想到這個系統這麼沒用。
[choice]: none
[scene]: hospital
[role]:  LuoYue
[item]: none
[dialog]: 老板願意給機會，我願意試試！
[choice]: none
[scene]: hospital
[role]:  Aside
[item]: none
[dialog]: 言煜祁看著面前眼睛閃閃發亮的女孩，不知道為什麼心情有些愉悅，嘴角微微上揚。
[choice]: none
[scene]: hospital
[role]:  YanYuQi
[item]: none
[dialog]: 林舟，你拿洛小姐的簡歷回去給人事登記一下。妳等等加一下林舟的聯繫方式，週一來報到。
[choice]: none
[scene]: hospital
[role]:  Aside
[item]: none
[dialog]: 得了兩人的回應後，言煜祁就先帶著林舟離開了，留下洛玥一個人仍處於震驚當中。
[choice]: none
[scene]: hospital
[role]:  LuoYue(think)
[item]: none
[dialog]: 我這任務進行的這麼順利的嗎…
[choice]: none
[[second_first_first.no]]
[scene]: hospital
[role]:  Aside
[item]: none
[dialog]: 洛玥驚到眼睛睜大，沒想到自己心裡所預期的計畫，甚至都還沒開始實施，就已經完成第一步了。
[choice]: none
[scene]: hospital
[role]:  LuoYue(think)
[item]: none
[dialog]: 統子統子，你不會給我開了什麼金手指吧？
[choice]: none
[scene]: hospital
[role]:  System
[item]: none
[dialog]: 沒有喔主人，新手禮包除了可以讓妳自己設定自身消息外，並沒有其他功能了喔！
[choice]: none
[scene]: hospital
[role]:  Aside
[item]: none
[dialog]: 洛玥忍不住在心裡放了白眼，也是沒想到這個系統這麼沒用。但這也引起洛玥的懷疑，沒想到進行的那麼順利，因此她決定先觀望觀望。
[choice]: none
[scene]: hospital
[role]:  LuoYue
[item]: none
[dialog]: 言總，這…不好吧，我沒經歷過貴公司的面試就直接入職，是不是不太恰當呢？
[choice]: none
[scene]: hospital
[role]:  Aside
[item]: none
[dialog]: 言煜祁看著眼前小心翼翼的小姑娘，想到她那個孤兒的身世跟自己幾乎一樣，沒來由地有些心疼。
[choice]: none
[scene]: hospital
[role]:  YanYuQi
[item]: none
[dialog]: 我看了你的簡歷我覺得很適合這個職位，包含你在學期間參與過的一些競賽，恰恰證明你是我要的人才。排除掉這些來說，你還是我同校學妹，幫助一下也是沒問題的。再說，怎麼沒有面試呢，現在不就是嗎？
[choice]: none
[scene]: hospital
[role]:  Aside
[item]: none
[dialog]: 洛玥看著面前的男人，有些吃驚。
[choice]: none
[scene]: hospital
[role]:  LuoYue(think)
[item]: none
[dialog]: 他不是高冷霸總嗎？怎麼反差這麼大啊…
[choice]: none
[scene]: hospital
[role]:  LuoYue
[item]: none
[dialog]: 既然言總這麼說，那我就恭敬不如從命。
[choice]: none
[scene]: hospital
[role]:  Aside
[item]: none
[dialog]: 得到女孩肯定答覆的言煜祁，不知道為什麼心情有些愉悅，嘴角微微上揚。
[choice]: none
[scene]: hospital
[role]:  YanYuQi
[item]: none
[dialog]: 林舟，你拿洛小姐的簡歷回去給人事登記一下。妳等等加一下林舟的聯繫方式，週一來報到。
[choice]: none
[scene]: hospital
[role]:  Aside
[item]: none
[dialog]: 得了兩人的回應後，言煜祁就先帶著林舟離開了，留下洛玥一個人仍處於震驚當中。
[choice]: none
[scene]: hospital
[role]:  LuoYue(think)
[item]: none
[dialog]: 我這任務進行的這麼順利的嗎…
[choice]: none
[[second_first.thanks]]
[scene]: hospital
[role]:  LuoYue
[item]: none
[dialog]: 感謝你們兩位把我送來醫院，我…有機會請二位吃個飯？
[choice]: none
[scene]: hospital
[role]:  LinZhou
[item]: none
[dialog]: 那倒不用，洛小姐妳沒事就行。
[choice]: none
[scene]: hospital
[role]:  Aside
[item]: none
[dialog]: 一直在一旁沒說話的言煜祁這時也站了起來。
[choice]: none
[scene]: hospital
[role]:  YanYuQi
[item]: none
[dialog]: 既然妳沒事，那我們就不打擾了，妳好好休息吧。
[choice]: none
[scene]: hospital
[role]:  Aside
[item]: none
[dialog]: 語畢，便帶頭走出病房，林舟對洛玥點了個頭也跟著出去了。
[choice]: none
[scene]: car
[role]:  Aside
[item]: none
[dialog]: 車子急駛在京市的道路上，言煜祁坐在車裡看著公司的資料，但腦子裡都是醫院裡少女的模樣。
[choice]: none
[scene]: car
[role]:  YanYuQi
[item]: none
[dialog]: 林舟，你方才去調查了洛玥結果如何。
[choice]: none
[scene]: car
[role]:  LinZhou
[item]: none
[dialog]: 總裁您放心，這個洛小姐不是我們競爭對手的人，單純就是低血糖暈倒在我們車子旁。她的詳細資料我已經發給總裁您了。
[choice]: none
[scene]: car
[role]:  Aside
[item]: none
[dialog]: 聞言，言煜祁拿出手機點開洛月的資料。
[choice]: none
[scene]: car
[role]:  YanYuQi
[item]: none
[dialog]: M大管理學院…林舟，你找時間去連絡一下洛玥，問問她要不要來當我的秘書，要是願意下禮拜一就能來上班。
[choice]: none
[scene]: car
[role]:  LinZhou
[item]: none
[dialog]: 總裁，確定您秘書的位置就是她了嗎？
[choice]: none
[scene]: car
[role]:  YanYuQi
[item]: none
[dialog]: 這樣的人才不管怎麼樣都要爭取來，而且我有預感她會對我有很大的助益，不管如何你想辦法說服她來言氏。
[choice]: none
[scene]: car
[role]:  LinZhou
[item]: none
[dialog]: 好的，總裁。
[choice]: none
[scene]: Yan's 
[role]:  Aside
[item]: smartphone
[dialog]: 兩天後，加班到午夜的言煜祁收到林舟的訊息。
[choice]: none
[scene]: Yan's 
[role]:  LinZhou(message)
[item]: smartphone
[dialog]: 總裁，洛小姐答應了。
[choice]: none
[scene]: Yan's 
[role]:  Aside
[item]: smartphone
[dialog]: 看到訊息的言煜祁嘴角微微上揚，辛苦一天的疲憊似乎都一掃而空。
[choice]: none